---
baseURL: "/"
title: Eureka Demo
theme: hugo-eureka
paginate: 3
copyright: '&copy; 2021 <a href="https://www.wangchucheng.com/">C. Wang</a> and <a
  href="https://www.ruiqima.com/">R. Ma</a>

'
enableEmoji: true
enableGitInfo: false
summaryLength: 75
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
markup:
  highlight:
    codeFences: false
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  category: categories
  tag: tags
  series: series
  author: authors
build:
  useResourceCacheWhen: always
