---
label: Blog post
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: boolean
  name: toc
  label: toc
- type: list
  name: authors
  label: authors
- type: text
  name: tags
  label: tags
- type: text
  name: categories
  label: categories
- type: text
  name: series
  label: series
- type: datetime
  name: date
  label: date
- type: datetime
  name: lastmod
  label: lastmod
- type: text
  name: featuredImage
  label: featuredImage
